blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('create', never_cache(PostCreateView.as_view()), name='post_create'),
    path('update/<slug:slug>', never_cache(PostUpdateView.as_view()), name='post_update'),
    path('delete/<slug:slug>', never_cache(PostDeleteView.as_view()), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

django_homework/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.views import *
from django.conf import settings

# from django_homework import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = pageNotFound

blog/models.py
from django.db import models
from django.urls import reverse

from users.models import User

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    """
    Класс для работы с моделью Постов.
    """
    name = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.CharField(max_length=255, unique=True,  verbose_name='URL')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='post/', verbose_name='Изображение', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Признак публикации', default=True)
    view_count = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0)
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    created_by = models.ForeignKey('users.User', verbose_name='Автор', on_delete=models.CASCADE, related_name='post',
                                   **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('name', 'slug', '-creation_date',)
        permissions = [
            (
                'can_change_post',
                'Can change post'
            ),
        ]

    def increase_views(self):
        """
        Метод увеличивает количество просмотров.
        """
        self.view_count += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from blog.models import Post
from blog.services import send_post_email


# Create your views here.

class PostListView(ListView):
    model = Post
    extra_context = {
        'title': 'SkyPulse',  # дополнение к статической информации
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        if self.request.user.has_perm('blog.can_change_post'):
            return queryset
        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.increase_views()
        if obj.view_count == 100:
            send_post_email(obj)
        return obj


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('name', 'content', 'image', 'is_published', 'user',)
    success_url = reverse_lazy('blog:post_list')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('name', 'content', 'image', 'is_published', 'user',)

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', args=[str(self.object.slug)])


def toggle_publish(request, slug):
    """
    Функция переключения поста.
    """
    post_detail = get_object_or_404(Post, slug=slug)
    if post_detail.is_published:
        post_detail.is_published = False
    else:
        post_detail.is_published = True

    post_detail.save()

    return redirect(reverse('blog:post_list'))


class PostAllListView(LoginRequiredMixin, ListView):
    model = Post
    extra_context = {
        'title': 'Все записи SkyPulse',  # дополнение к статической информации
    }

blog/templates/blog/includes/inc_post_card.html
{% load mediapath %}

<div class="col-3 p-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-2 font-weight-normal">{{object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{object.content|slice:":136"}}</li>
                        </ul>
                        <p><img src="{% mediapath object.image %}" width="250" height="190" alt="Картинка"></p>
                        <p><a class="btn btn-secondary" href="{% url 'blog:post_detail' object.slug %}" role="button">Посмотреть &raquo</a></p>
                        {% if user.is_authenticated and object.user == user.email or perms.blog.can_change_post or user.is_superuser%}
                        <p><a class="btn btn-warning" href="{% url 'blog:post_update' object.slug %}" role="button">Изменить &raquo;</a></p>
                         {% endif %}
                        {% if user.is_superuser %}
                        <p><a class="btn btn-danger" href="{% url 'blog:post_delete' object.slug %}" role="button">Удалить &raquo;</a></p>
                        {% endif %}
                    </div>
                    {% if perms.blog.can_change_post or user.is_superuser %}
                    {% if  object.is_published %}
                        <a class="btn btn-danger" href="{% url 'blog:toggle_publish' object.slug %}" role="button">Deactivate &raquo;</a>
                    {% else %}
                        <a class="btn btn-success" href="{% url 'blog:toggle_publish' object.slug %}" role="button">Activate &raquo;</a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>