blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('create', never_cache(PostCreateView.as_view()), name='post_create'),
    path('update/<slug:slug>', never_cache(PostUpdateView.as_view()), name='post_update'),
    path('delete/<slug:slug>', never_cache(PostDeleteView.as_view()), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

catalog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from .views import *


app_name = CatalogConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # http://127.0.0.1:8000/
    path('contacts', ContactView.as_view(), name='contacts'),  # http://127.0.0.1:8000/contacts/
    path('categories', CategoriesListView.as_view(), name='categories_list'),
    path('products', never_cache(ProductListView.as_view()), name='product_list'),
    path('products/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('products/update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('products/delete/<int:pk>', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('product/toggle/<int:pk>', login_required(toggle_publish), name='toggle_publish'),
    path('allproducts', ProductAllListView.as_view(), name='all_products'),
]

django_homework/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.views import *
from django.conf import settings

# from django_homework import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = pageNotFound

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', ProfileUpdateView.as_view(), name='profile'),
    path('list', UserListView.as_view(), name='list'),
    path('register', RegisterView.as_view(), name='register'),
    path('activate/<str:token>', activate_user, name='activate'),
    path('page_after_registration/<str:token>', page_after_registration, name='page_after_registration'),
    path('profile/gennpassword', generate_new_password, name='generate_new_password'),
    path('set_is_active_users/<int:pk>', login_required(set_is_active_users), name='set_is_active_users'),
]

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """
    Класс модели Категории продукта.
    """
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}  ( {self.description} )'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)  # сортировка, '-name' - сортировка в обратном порядке


class Product(models.Model):
    """
    Класс модели Продукта.
    """
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    # category = models.CharField(max_length=150, verbose_name='Категория')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    creation_date = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    modification_date = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    # created_by = models.ForeignKey('users.User', verbose_name='Кем создано', on_delete=models.CASCADE, **NULLABLE)
    is_published = models.BooleanField(verbose_name='Признак публикации', default=False)

    is_active = models.BooleanField(default=True, verbose_name='Доработка программы под ваши требования')

    def __str__(self):
        return f'{self.name}'

    # {self.category}, {self.price}, {self.modification_date}'

    def get_absolute_url(self):
        return reverse('catalog:product_detail', kwargs={'pk': self.pk})

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'программный продукт'
        verbose_name_plural = 'программные продукты'
        ordering = ('name', 'category', 'price', 'modification_date',)
        permissions = [
            (
                'can_change_product',
                'Can change product'
            ),
        ]


class Version(models.Model):
    """
    Класс модели Версии Продукта.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number_version = models.IntegerField(verbose_name='Номер версии')
    title_version = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='Активная версия', default=True)

    def __str__(self):
        return f'{self.number_version} ({self.product})'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

import django_homework.settings
from catalog.models import *


class FormStyleMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


# импорт форм в views.py
class ProductForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)  # исключает поле из формы

    def clean_name(self):
        """
        Функция проверяет (валидирует) исключения загрузки продуктов, если в их названии есть запрещенная тематика.
        """
        cleaned_data = self.cleaned_data['name']
        for word in django_homework.settings.FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика в названии продукта - "{word}"')
        return cleaned_data

    def clean_description(self):
        """
        Функция проверяет (валидирует) исключения загрузки продуктов, если в их описании есть запрещенная тематика.
        """
        cleaned_data = self.cleaned_data['description']
        for word in django_homework.settings.FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика в описании продукта - "{word}"')
        return cleaned_data


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        # exclude = ('is_active',)  # исключает поле из формы

    def clean_is_active(self):
        """
        Проверка валидности только одной активной версии продукта.
        """
        cleaned_data = self.cleaned_data['is_active']

        if cleaned_data and self.instance.product.version_set.filter(is_active=True).exclude(
                id=self.instance.id).exists():
            raise forms.ValidationError('Может существовать только одна активная версия!')
        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory, formset_factory

from django.http import HttpResponse, HttpResponseNotFound, request
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_product_from_cashe


# Create your views here.


class IndexView(TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'SkyStore',
    }


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Обратная связь',
    }

    def post(self, request, *args, **kwargs):
        """
        Метод реализует обработку сбора обратной связи от пользователя, который зашел на страницу контактов и отправил
        свои данные для обратной связи.
        """
        name = request.POST.get('name', '')
        phone = request.POST.get('phone', '')
        message = request.POST.get('message', '')
        print(f'Contact information received: User {name} with phone {phone} send message: {message}')
        return render(request, self.template_name)


class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):  # меняет title на __str__.object (категория продукта)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_product_from_cashe  # логика вынесена в services.py
        return context_data


class ProductListView(ListView):
    """
    Класс для работы с моделью Продуктов.
    """
    model = Product
    extra_context = {
        'version_list': Version.objects.filter(is_active=True),
        'title': 'Каталог программных продуктов SkyStore',
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        if self.request.user.has_perm('catalog.can_change_product'):
            return queryset
        return queryset


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для получения деталей (единиц) модели Продуктов.
    """
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Класс создания новых единиц продуктов для модели Продуктов.
    """
    model = Product
    form_class = ProductForm
    # fields = ('name', 'description', 'image', 'category', 'price')
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        """Метод добавления создателя продукта"""
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormSet = formset_factory(VersionForm, extra=1)
        context['version_formset'] = VersionFormSet()
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    Класс для обновления единиц продуктов для модели Продуктов.
    """
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form_with_formset.html'
    # fields = ('name', 'description', 'image', 'category', 'price')
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)  # extra= 2 выведет 2 формы
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST,
                                                     instance=self.object)  # instance=self.object выводит ещё одну форму
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """
    Класс для удаления единиц продуктов из модели Продуктов.
    """
    model = Product
    success_url = reverse_lazy('catalog:product_list')


def toggle_publish(request, pk):
    """
    Функция переключения публикации программных продуктов.
    """
    product_detail = get_object_or_404(Product, pk=pk)
    if product_detail.is_published:
        product_detail.is_published = False
    else:
        product_detail.is_published = True

    product_detail.save()

    return redirect(reverse('catalog:product_detail', args=[product_detail.pk]))


class ProductAllListView(LoginRequiredMixin, ListView):
    model = Product
    extra_context = {
        'title': 'Все программные продукты SkyStore',  # дополнение к статической информации
    }


class VersionListView(LoginRequiredMixin, ListView):
    model = Version
    extra_context = {
        'object_list': Version.objects.filter(is_active=True),
        'title': 'Все версии'
    }


class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class VersionDetailView(LoginRequiredMixin, DetailView):
    model = Version

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


def pageNotFound(request, exception):
    """
    Функция для корректного отображения страницы при ошибке Http404 (pageNotFound).
    Только при mode DEBUG off.
    """
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

catalog/templates/catalog/includes/inc_main_menu.html
<nav class="ms-5">
        <a  title="Здесь можно посмотреть каталог представленных товаров"  class="p-2 btn btn-outline-primary border-warning mx-1" href="{% url 'catalog:product_list' %}">Каталог</a>
        <a title="Свяжитесь с нами" class="p-2 btn btn-outline-primary border-warning" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a title="SkyPulse - держи руку на Пульсе!" class="p-2 btn btn-outline-primary border-warning mx-1" href="{% url 'blog:post_list' %}">Блог</a>

     {% if user.is_authenticated %}
            <a  title="Все о тебе)" class="p-2 btn btn-outline-primary border-warning" href="{% url 'users:profile' %}">Профиль</a>  <!-- динамическая ссылка на url -->
            <a  title="До свидания!" class="p-2 btn btn-outline-primary border-warning mx-1" href="{% url 'users:logout' %}">Выйти</a>  <!-- динамическая ссылка на url -->
    {% else %}
            <a title="Присоединяйся!" class="p-2 btn btn-outline-primary border-warning" href="{% url 'users:register' %}">Регистрация</a>  <!-- динамическая ссылка на url -->
            <a title="Давай к нам!" class="p-2 btn btn-outline-primary border-warning mx-1" href="{% url 'users:login' %}">Войти</a>  <!-- динамическая ссылка на url -->

    {% endif %}

    </nav>

catalog/templates/catalog/includes/inc_product_card.html
{% load mediapath %}
<div class="container">
        <div class=" row-8 text-center ">
            <img class="rounded-circle col-6 mt-5" src="{% mediapath object.image %}" alt="Картинка" width="660" height="440"/>
            <div class="row-8  p-1">
                <div class="card mb-4 box-shadow text-center ">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title pricing-card-title"> {{object.category}}</h5>
                        <h5 class="card-title pricing-card-title"> {{object.price}} ₽</h5>
                        <ul class="list-unstyled mt-3 mb-6 text-center">
                            <li>{{object.description|slice:":100"}}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block border-warning btn-primary"><a class="text-light" href="mailto:my_danny@mail.ru" target="_blank" title="Оформите заказ, связавшись с нами">Сделать Заказ</a></button>
                    </div>
                     <ul class="list-unstyled mt-3 mb-4 text-start m-5">

                            {% for version in object.version_set.all %}
                                 {% if version.is_active %}

                                    <div><strong>Активная версия: </strong> {{ version.number_version}} - {{ version.title_version}}</div>
                                 {% endif %}
                            {% endfor %}

                        </ul>
                    <p><a class="btn btn-secondary border-warning " href="{% url 'catalog:product_detail' object.pk %}">Посмотреть &raquo;</a>
                  {% if user.is_authenticated and object.user == user.email or perms.catalog.can_change_product or user.is_superuser%}
                    <a class="btn btn-warning border-danger" href="{% url 'catalog:product_update' object.pk %}">Изменить &raquo;</a>
                   {% endif %}
                        {% if user.is_superuser %}
                    <a class="btn btn-danger border-warning" href="{% url 'catalog:product_delete' object.pk %}">Удалить &raquo;</a></p>
                {% endif %}
                </div>
                {% if perms.catalog.can_change_product or user.is_superuser %}
                    {% if  object.is_published %}
                        <a class="btn btn-danger" href="{% url 'catalog:toggle_publish' object.pk %}" role="button">Снять с публикации &raquo;</a>
                    {% else %}
                        <a class="btn btn-success" href="{% url 'catalog:toggle_publish' object.pk %}" role="button">Опубликовать &raquo;</a>
                    {% endif %}
                    {% endif %}
            </div>
        </div>
    </div>