blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('create', never_cache(PostCreateView.as_view()), name='post_create'),
    path('update/<slug:slug>', never_cache(PostUpdateView.as_view()), name='post_update'),
    path('delete/<slug:slug>', never_cache(PostDeleteView.as_view()), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

catalog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from .views import *


app_name = CatalogConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # http://127.0.0.1:8000/
    path('contacts', ContactView.as_view(), name='contacts'),  # http://127.0.0.1:8000/contacts/
    path('categories', CategoriesListView.as_view(), name='categories_list'),
    path('products', never_cache(ProductListView.as_view()), name='product_list'),
    path('products/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('products/update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('products/delete/<int:pk>', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('product/toggle/<int:pk>', login_required(toggle_publish), name='toggle_publish'),
    path('allproducts', ProductAllListView.as_view(), name='all_products'),
]

django_homework/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.views import *
from django.conf import settings

# from django_homework import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = pageNotFound

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', ProfileUpdateView.as_view(), name='profile'),
    path('list', UserListView.as_view(), name='list'),
    path('register', RegisterView.as_view(), name='register'),
    path('activate/<str:token>', activate_user, name='activate'),
    path('page_after_registration/<str:token>', page_after_registration, name='page_after_registration'),
    path('profile/gennpassword', generate_new_password, name='generate_new_password'),
    path('set_is_active_users/<int:pk>', login_required(set_is_active_users), name='set_is_active_users'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from django.db import models
from django.apps import apps


# Create your models here.


NULLABLE = {'blank': True, 'null': True}



class UserManager(BaseUserManager):
    """
    Класс переопределение модели для команды python manage.py createsuperuser (для поля email).
    """
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Function created and save a user with the given username, email, and password.
        """

        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Класс для работы с моделью User (пользователя).
    """
    username = None
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    avatar = models.ImageField(upload_to='user/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=50, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='Страна', **NULLABLE)
    token = models.CharField(max_length=15, verbose_name='Токен', **NULLABLE)
    token_time = models.DateTimeField(auto_now_add=True, verbose_name='Время создания токена', **NULLABLE)
    is_active = models.BooleanField(default=True,  verbose_name='Активный')

    # Переопределение настроек для авторизации и регистрации через модель
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return f'{self.email}'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('email',)
        permissions = [
            ('can_block_users', 'Can block users'),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import User


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(FormStyleMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'country', 'first_name', 'last_name', 'avatar', 'phone',)

    def __init__(self, *args, **kwargs):
        """
        Метод инициализирует сокрытие пароля.
        """
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'country',)

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView, ListView

from django_homework import settings
from users.forms import UserForm, UserRegisterForm
from users.models import User
from users.services import account_confirmation


# Create your views here.


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('catalog:index')

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = f'/users/page_after_registration/'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.user_token = None

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            self.object.is_active = False
            self.object.token = secrets.token_urlsafe(18)[:15]
            account_confirmation(self.object)
            self.object.save()
            self.user_token = self.object.token
            self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        """
        Метод создает уникальный URL адрес для подтверждения регистрации.
        """
        new_url = super().get_success_url()
        token = self.object.token
        return str(new_url) + str(token)


def page_after_registration(request, token):
    """
    Функция после отправки запроса на верификацию, перенаправляет на страницу ожидания подтверждения пароля.
    """
    if request.method == 'POST':
        obj = get_object_or_404(User, token=token)
        account_confirmation(obj)
    return render(request, 'users/page_after_registration.html')


def activate_user(request, token):
    """
    Функция активирует деактивированного пользователя.
    """
    user = User.objects.filter(token=token).first()
    if user:
        user.is_active = True
        user.save()
        return redirect('users:login')
    return render(request, 'users/user_not_found.html')


def generate_new_password(request):
    """
    Функция генерирует новый пароль и отправляет его на почту пользователя.
    """
    pass_ch = secrets.token_urlsafe(18)[:12]
    send_mail(
        subject='Смена пароля',
        message=f'Ваш новый пароль {pass_ch}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    # print(pass_ch)
    request.user.set_password(pass_ch)
    request.user.save()
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, ListView):
    model = User
    fields = ("email",)
    extra_context = {
        'title': 'Пользователи'
    }

    def get_queryset(self):
        return super().get_queryset().order_by('pk')


def set_is_active_users(request, pk):
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True
    user_item.save()
    return redirect(reverse('users:list'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success mt-3" type="submit">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/page_after_registration.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Спасибо за регистрацию!</h1>
        <br>
        <h5 class="display-8">Для подтверждения аккаунта, на почту была отправлена ссылка, перейдите по ней для
            завершения регистрации</h5>
        <form method="post">
            {% csrf_token %}
            <input class="p-2 btn btn-dark" type="submit" name="upvote" value="Отправить повторно"/>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            <!-- enctype="multipart/form-data" сохраняет форму и добавляет медиа(аватар) -->
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="form-group text-center">

                                <a href="{% url 'catalog:product_list' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                             {% if user.is_authenticated or user.is_superuser%}
                            <div class="card-footer">
                            <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Изменить пароль!
                                Будьте внимательны, новый пароль будет отправлен вам на электронную почту!</a>
                              {%endif%}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'catalog/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load static %}

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <main>
        <div class="pricing-header px-1 py-1 pt-md-1 pb-md-1 mx-auto text-center">
<!--            <img class="rounded-circle" src="{% static 'img/main/forest.jpg' %}" alt="Картинка" width="500" height="300">-->
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

            {% for object in object_list %}
                {% if user.is_authenticated and object.created_by == user or user.is_superuser or perms.users.can_block_users %}
                    <div class="col">
                        <div class="card mb-4  rounded-3 shadow-sm">
                            <div class="card-header py-3">
                                <h5 class="my-0 fw-normal">{{ object.first_name}} {{object.last_name }}</h5>
                            </div>
                            <div class="card-body bg-secondary" >
                                <h6 class="card-title text-light pricing-card-title">{{ object.email }}</h6>

                                {% if user.is_superuser or perms.users.can_block_users %}
                        <a href="{% url 'users:set_is_active_users' object.pk %}" class="btn btn-outline-warning float-end mt-3">
                            {% if object.is_active %}
                                Деактивировать
                            {% else %}
                                Активировать
                            {% endif %}
                        </a>
                        {% endif %}

                                {%endif%}

           <div><p class="card-title text-warning">(╯‵□)╯︵┴─┴</p></div>

<table class="table mt-5">
                            <tbody>
                            <tr>
                                <td>
                                    <p class="card-text"><b>Телефон:</b> {{ object.phone }}</p>
                                    <p class="card-text"><b>Страна:</b> {{ object.country }}</p>
                                </td>
                                <td>
                                    <p class="card-text"><b>Активный (is_active):</b> {{ object.is_active }}</p>
                                    <p class="card-text"><b>Администратор:</b> {{ object.is_superuser }}</p>
                                    <p class="card-text"><b>Сотрудник:</b> {{ object.is_stuff }}</p>
                                </td>
                                <td>
                                    <p class="card-text"><b>Дата создания:</b> {{ object.date_joined }}</p>
                                    <p class="card-text"><b>Последний логин:</b> {{ object.last_login }}</p>
                                </td>
                            </tr>
                            </tbody>
                        </table>

                            </div>
                        </div>
                    </div>

            {% endfor %}
        </div>
    </main>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

users/templates/users/user_not_found.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Ошибка!</h1>
        <h1 class="display-8">Аккаунт не найден.</h1>
        <br>
        <h5 class="display-8">Возможно прошло слишком много времени с момента регистрации, попробуйте повторно перейти по ссылке из сообщения или зарегистрироваться заново</h5>
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:register' %}">Рeгистрация</a>
    </div>

{% endblock %}