blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', cache_page(60)(PostDetailView.as_view()), name='post_detail'),
    path('create', never_cache(PostCreateView.as_view()), name='post_create'),
    path('update/<slug:slug>', never_cache(PostUpdateView.as_view()), name='post_update'),
    path('delete/<slug:slug>', never_cache(PostDeleteView.as_view()), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

catalog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from .views import *


app_name = CatalogConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # http://127.0.0.1:8000/
    path('contacts', ContactView.as_view(), name='contacts'),  # http://127.0.0.1:8000/contacts/
    path('categories', CategoriesListView.as_view(), name='categories_list'),
    path('products', never_cache(ProductListView.as_view()), name='product_list'),
    path('products/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('products/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('products/update/<int:pk>', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('products/delete/<int:pk>', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('product/toggle/<int:pk>', login_required(toggle_publish), name='toggle_publish'),
    path('allproducts', ProductAllListView.as_view(), name='all_products'),
]

django_homework/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from catalog.views import *
from django.conf import settings

# from django_homework import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = pageNotFound

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """
    Класс модели Категории продукта.
    """
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}  ( {self.description} )'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)  # сортировка, '-name' - сортировка в обратном порядке


class Product(models.Model):
    """
    Класс модели Продукта.
    """
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    # category = models.CharField(max_length=150, verbose_name='Категория')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    creation_date = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    modification_date = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    # created_by = models.ForeignKey('users.User', verbose_name='Кем создано', on_delete=models.CASCADE, **NULLABLE)
    is_published = models.BooleanField(verbose_name='Признак публикации', default=False)

    is_active = models.BooleanField(default=True, verbose_name='Доработка программы под ваши требования')

    def __str__(self):
        return f'{self.name}'

    # {self.category}, {self.price}, {self.modification_date}'

    def get_absolute_url(self):
        return reverse('catalog:product_detail', kwargs={'pk': self.pk})

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'программный продукт'
        verbose_name_plural = 'программные продукты'
        ordering = ('name', 'category', 'price', 'modification_date',)
        permissions = [
            (
                'can_change_product',
                'Can change product'
            ),
        ]


class Version(models.Model):
    """
    Класс модели Версии Продукта.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number_version = models.IntegerField(verbose_name='Номер версии')
    title_version = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='Активная версия', default=True)

    def __str__(self):
        return f'{self.number_version} ({self.product})'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

import django_homework.settings
from catalog.models import *


class FormStyleMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


# импорт форм в views.py
class ProductForm(FormStyleMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)  # исключает поле из формы

    def clean_name(self):
        """
        Функция проверяет (валидирует) исключения загрузки продуктов, если в их названии есть запрещенная тематика.
        """
        cleaned_data = self.cleaned_data['name']
        for word in django_homework.settings.FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика в названии продукта - "{word}"')
        return cleaned_data

    def clean_description(self):
        """
        Функция проверяет (валидирует) исключения загрузки продуктов, если в их описании есть запрещенная тематика.
        """
        cleaned_data = self.cleaned_data['description']
        for word in django_homework.settings.FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика в описании продукта - "{word}"')
        return cleaned_data


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        # exclude = ('is_active',)  # исключает поле из формы

    def clean_is_active(self):
        """
        Проверка валидности только одной активной версии продукта.
        """
        cleaned_data = self.cleaned_data['is_active']

        if cleaned_data and self.instance.product.version_set.filter(is_active=True).exclude(
                id=self.instance.id).exists():
            raise forms.ValidationError('Может существовать только одна активная версия!')
        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory, formset_factory

from django.http import HttpResponse, HttpResponseNotFound, request
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_category_product_from_cashe


# Create your views here.


class IndexView(TemplateView):
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'SkyStore',
    }


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {
        'title': 'Обратная связь',
    }

    def post(self, request, *args, **kwargs):
        """
        Метод реализует обработку сбора обратной связи от пользователя, который зашел на страницу контактов и отправил
        свои данные для обратной связи.
        """
        name = request.POST.get('name', '')
        phone = request.POST.get('phone', '')
        message = request.POST.get('message', '')
        print(f'Contact information received: User {name} with phone {phone} send message: {message}')
        return render(request, self.template_name)


class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):  # меняет title на __str__.object (категория продукта)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_product_from_cashe  # логика вынесена в services.py
        return context_data


class ProductListView(ListView):
    """
    Класс для работы с моделью Продуктов.
    """
    model = Product
    extra_context = {
        'version_list': Version.objects.filter(is_active=True),
        'title': 'Каталог программных продуктов SkyStore',
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        if self.request.user.has_perm('catalog.can_change_product'):
            return queryset
        return queryset


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для получения деталей (единиц) модели Продуктов.
    """
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Класс создания новых единиц продуктов для модели Продуктов.
    """
    model = Product
    form_class = ProductForm
    # fields = ('name', 'description', 'image', 'category', 'price')
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        """Метод добавления создателя продукта"""
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormSet = formset_factory(VersionForm, extra=1)
        context['version_formset'] = VersionFormSet()
        return context


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    Класс для обновления единиц продуктов для модели Продуктов.
    """
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form_with_formset.html'
    # fields = ('name', 'description', 'image', 'category', 'price')
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)  # extra= 2 выведет 2 формы
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST,
                                                     instance=self.object)  # instance=self.object выводит ещё одну форму
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """
    Класс для удаления единиц продуктов из модели Продуктов.
    """
    model = Product
    success_url = reverse_lazy('catalog:product_list')


def toggle_publish(request, pk):
    """
    Функция переключения публикации программных продуктов.
    """
    product_detail = get_object_or_404(Product, pk=pk)
    if product_detail.is_published:
        product_detail.is_published = False
    else:
        product_detail.is_published = True

    product_detail.save()

    return redirect(reverse('catalog:product_detail', args=[product_detail.pk]))


class ProductAllListView(LoginRequiredMixin, ListView):
    model = Product
    extra_context = {
        'title': 'Все программные продукты SkyStore',  # дополнение к статической информации
    }


class VersionListView(LoginRequiredMixin, ListView):
    model = Version
    extra_context = {
        'object_list': Version.objects.filter(is_active=True),
        'title': 'Все версии'
    }


class VersionUpdateView(LoginRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:product_list')


class VersionDetailView(LoginRequiredMixin, DetailView):
    model = Version

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


def pageNotFound(request, exception):
    """
    Функция для корректного отображения страницы при ошибке Http404 (pageNotFound).
    Только при mode DEBUG off.
    """
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="header-blue">
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-dark border-bottom border-warning box-shadow">
 <h5 title="Вернуться на главную страницу" class="my-0 mr-md-auto font-weight-normal p-0"><a href="/"><div class="logo"></div></a></h5>
        {% include 'catalog/includes/inc_main_menu.html' %}
    <!-- ШАБЛОННЫЙ ТЕГ include вставляет отдельный html из файла 'inc_main_menu.html' -->
</div>
   <div class="header-blue">
{% block content %}


{% endblock %}
<!--   <div class="header-blue">-->

<div class="container">

    <footer class="pt-4 my-md-5 pt-md-5 border-top border-warning">
        <div class="row">
            <div style="color:#c0c0c0" class="col-12 col-md ">
                SkyStore
                <small style="color:#c0c0c0" class="d-block mb-3">&copy; 2023</small>
            </div>
            <div class="col-6 col-md ">
                <h5> <a style="color:#c0c0c0" href="{% url 'catalog:categories_list' %}"> Категории </a></h5>
<!--                <ul class="list-unstyled text-small">-->
<!--                    <li><a class="text-muted" href="#">Рассылки</a></li>-->
<!--                    <li><a class="text-muted" href="#">Телеграм боты</a></li>-->
<!--                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>-->
<!--                    <li><a class="text-muted" href="#">Веб-приложения</a></li>-->
<!--                    <li><a class="text-muted" href="#">Микросервисы</a></li>-->
<!--                </ul>-->
            </div>
            <div style="color:#c0c0c0" class="col-6 col-md ">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a style="color:#c0c0c0" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div style="color:#c0c0c0" class="col-6 col-md ">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a title="Свяжитесь с нами" style="color:#c0c0c0" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>

    </footer>
</div>

    </div>
              </div>
     <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}  <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
<figure class=" p-3 mb-0" style="color:#00ffff">
    {% for category in object_list %}
        <h6> Название категории: {{ category.name }}</h6>
        <h6> Описание: {{ category.description }}</h6>
         <p>----------</p>
    {% endfor %}
    </figure>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
<!--                        <input class="btn btn-primary" type="submit" value="Отправить"/>-->
                        <button type="submit" class="btn btn-lg btn-block border-success btn-outline-primary">Отправить</button>
                    </form>

<!--                    <input type="submit">-->
<!--                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>-->
                </div>
            <!-- </form> -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4 text-info">SkyStore</h1>
    <p class="lead text-warning">SkyStore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container ">
    <div class="row text-center ">
        <div class="col-3 ">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <div class="row">
                    <button type="button" class="btn btn-lg btn-block border-success btn-primary"><a class="text-warning" href="mailto:my_danny@mail.ru" target="_blank" title="Оформите заказ, связавшись с нами">Купить</a></button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-9">
        <img src="{% static 'img/catalog/all_products.jpg' %}" alt="Картинка"  width="560" height="340"/>

                        </div>
                    </div>
                </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены, что хотите удалить программный продукт "{{ object.name }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:product_list' %}" class="btn btn-primary border-info"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mediapath %}
{% block content %}

    <div class="col">
        <div class=" row-8  mt-0 p-1">
                            <img  src="{% mediapath 'image/all_products.jpg' %}" alt="Картинка"  width="560" height="340"/>
            </div>
        <div class="card mx-1">
            <div class="card-body">
                <table class="table">
<!--                    <img src="{% mediapath 'image/all_products.jpg' %}" alt="Картинка"  width="560" height="340"/>-->
                    <tr>
                        <td>Наименование</td>
                        <td>{{object.name}}</td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ object.description|linebreaks }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ object.category }}</td>
                    </tr>
                    <tr>
                        <td>Цена</td>
                        <td>{{ object.price }} руб</td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td>{{ object.creation_date }}</td>
                    </tr>
                    <tr>
                        <td>Дата изменения</td>
                        <td>{{ object.modification_date }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'catalog:product_list' %}" class="btn btn-primary border-info mx-1"><< Назад</a>
        </div>
    </div>
{% endblock %}
</main>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                <!-- enctype="multipart/form-data" сохраняет форму и добавляет медиа(картинку) -->
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" class="btn btn-success border-warning"  value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'catalog:product_list' %}" class="btn btn-primary border-info"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Сохранить{% else %} Создать {% endif %}">
                        <!-- ШАБЛОННЫЙ ТЕГ Условия -->

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        Версии
                    </div>
                    <div class="card-body">
                        <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="subject-form">
                                    <td>{{ form.as_p }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}

{% if user.is_authenticated  or user.is_superuser %}
<div class="col-12">
        <a href="{% url 'catalog:product_create' %}" class="btn btn-primary border-info mx-3 m-12 mt-3">Создать продукт</a>
      {% endif %}
     {% if perms.catalog.can_change_product or user.is_superuser %}
    <a href="{% url 'catalog:all_products' %}" class="btn btn-primary border-info mx-3 m-12 mt-3">Показать все продукты</a>
      {% endif %}
    </div>
 <figure class=" p-3 mb-0" style="color:#00ffff">
{% for version in version_list %}
        <h6> Активная версия: {{ version.title_version }}</h6>
        <h6> Номер версии: {{ version.number_version }}</h6>
        <h6> Продукт версии: {{ version.product }}</h6>
     <p>----------</p>

    {% endfor %}
</figure>
     <div class="container">
    {% if object_list %}
        <div class="row text-center">
{% for object in object_list %}
    {% include 'catalog/includes/inc_product_card.html' %}
{% endfor %}
  </div>
  {% else %}
        <h3 style="color:#FF8C00">Нет доступных программных продуктов</h3>
    <h3 style="color:#FF8C00">:-(</h3>
    {% endif %}
  </div>
<p></p>
<div class="container">
        <div class="row">
            <div style="color:#c0c0c0" class="col-12 col-md ">
                В данном проекте используются настоящие объявления, взятые в учебных целях с сайта https://kwork.ru/categories/software  и  https://kwork.ru/categories/script-programming.
            </div>
       </div>
    </div>
{% endblock %}